Updated install scripts for bsts and Boom.
- Add -i option to handle installation.

- Add -c option to request R CMD CHECK.

diff --git a/install/bsts b/install/bsts
--- a/install/bsts
+++ b/install/bsts
@@ -1,15 +1,58 @@
 #!/bin/bash
 
+usage () { echo "Usage: $0 [-c] [-i] 1>&2; exit 0"; }
+
+DO_INSTALL=0
+DO_CHECK=0
+
+while getopts :ci option; do
+    case "${option}" in
+        i)
+            DO_INSTALL=1
+            ;;
+        c)
+            DO_CHECK=1
+            ;;
+        \?)
+	    echo "Invalid option: -$OPTARG" >&2
+            usage
+            ;;
+    esac
+done
+shift $((OPTIND-1))
+
+## If the rpackage directory does not exist then create it.
+if [ ! -d rpackage ]; then
+    mkdir rpackage
+fi
+
 BSTSDIR='rpackage/bsts'
-## If there is already a Boom directory then delete it.
+## If there is already an rpackage/bsts directory then delete it.
 if [ -d "$BSTSDIR" ]; then
    rm -rf $BSTSDIR
 fi
 
-if [ -d rpackage ]; then
-    mkdir rpackage
-fi
-
 cp -r ./Interfaces/R/bsts rpackage
 cd rpackage
+if [ -d bsts/tests ]; then
+    if [ ! -d bsts/inst ]; then
+	mkdir bsts/inst
+    fi
+    mv bsts/tests bsts/inst/tests
+fi
+
+if [ -f bsts_*.tar.gz ]; then
+    rm bsts_*.tar.gz
+fi
+
 R CMD BUILD bsts
+
+if [[ $DO_CHECK = 1 ]]; then
+    echo "Checking package"
+    MAKEFLAGS=" -j 8 " R CMD CHECK bsts_*.tar.gz
+fi
+
+if [[ $DO_INSTALL = 1 ]]; then
+    echo "Installing package"
+    MAKEFLAGS=" -j 8 " R CMD INSTALL bsts_*.tar.gz
+fi
diff --git a/install/create_boom_rpackage b/install/create_boom_rpackage
--- a/install/create_boom_rpackage
+++ b/install/create_boom_rpackage
@@ -1,5 +1,26 @@
 #!/bin/bash
 
+usage () { echo "Usage: $0 [-c] [-i] 1>&2; exit 0"; }
+
+DO_INSTALL=0
+DO_CHECK=0
+
+while getopts :ci option; do
+    case "${option}" in
+        i)
+            DO_INSTALL=1
+            ;;
+        c)
+            DO_CHECK=1
+            ;;
+        \?)
+	    echo "Invalid option: -$OPTARG" >&2
+            usage
+            ;;
+    esac
+done
+shift $((OPTIND-1))
+
 BOOM_DIR='rpackage/Boom'
 
 ## If there is already a Boom directory then delete it.
@@ -85,16 +106,15 @@ echo "Ignore the message about not being able to copy Eigen/src."
 ## Build the package:
 
 cd rpackage
-VERSION=`grep 'Version' Boom/DESCRIPTION | awk -F':' '{print $2}' | tr -d [:space:]`
-fname="Boom_$VERSION.tar.gz"
+
 R CMD build Boom
 
-## To check the package:
-# -k means 'keep going' in the event of an error.
-# -j 8 means use 8 threads in the build.
-#
-# MAKEFLAGS="-k j 8 " R CMD CHECK $fname
+if [[ $DO_CHECK = 1 ]]; then
+    MAKEFLAGS=" j 8 " R CMD CHECK Boom_*.tar.gz
+fi
 
-## To install the package
-# MAKEFLAGS="-k j 8 " R CMD INSTALL $fname
+if [[ $DO_INSTALL = 1 ]]; then
+    MAKEFLAGS=" j 8 " R CMD INSTALL Boom_*.tar.gz
+fi
+
 
